# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service as ChromiumService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import ChromeType


class Driver():
  def __init__(self):
    self.driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
    # self.driver.set_window_size(651, 703)
  
  
  def close(self):
    self.driver.quit()
  
  def redirect(self, url):
    self.driver.get(url)

  
if __name__ == "__main__":
  t = Driver()
  t.test_loginasLucius()
  t.close()
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

  